// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Valasztas.Models;

#nullable disable

namespace Valasztas.Migrations
{
    [DbContext(typeof(ValasztasDbContext))]
    [Migration("20240925092950_sqlite.local_migration_667")]
    partial class sqlitelocal_migration_667
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.8");

            modelBuilder.Entity("Valasztas.Models.Jelolt", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Kerulet")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Partrovidnev")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("szavazatszam")
                        .HasColumnType("INTEGER");

                    b.HasKey("id");

                    b.HasIndex("Partrovidnev");

                    b.ToTable("Jeloltek");
                });

            modelBuilder.Entity("Valasztas.Models.Part", b =>
                {
                    b.Property<string>("rovidnev")
                        .HasColumnType("TEXT");

                    b.Property<string>("hosszunev")
                        .HasColumnType("TEXT");

                    b.HasKey("rovidnev");

                    b.ToTable("Partok");
                });

            modelBuilder.Entity("Valasztas.Models.Jelolt", b =>
                {
                    b.HasOne("Valasztas.Models.Part", "Part")
                        .WithMany("Jeloltek")
                        .HasForeignKey("Partrovidnev")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Part");
                });

            modelBuilder.Entity("Valasztas.Models.Part", b =>
                {
                    b.Navigation("Jeloltek");
                });
#pragma warning restore 612, 618
        }
    }
}
